In [6]:
# First Class(Numpy): Fri 2025/02/14

In [1]:
import numpy as np

In [15]:
arr = np.array([1,2,3,4])
print(arr)
np.mean(arr)

[1 2 3 4]


2.5

## Class Work:

In [ ]:
# Create a 1D array with values ranging from 0 to 9

In [30]:
arr_2 = np.arange(10)
print(arr_2)

[0 1 2 3 4 5 6 7 8 9]


## Home Work:

In [2]:
# Convert a 1D array to a 2D array with 2 rows

In [16]:
arr_3 = np.reshape(arr, (2,2))
arr_3

array([[1, 2],
       [3, 4]])

In [4]:
# Extract all odd numbers from an array of 1-10

In [24]:
arr_4 = np.arange(11)
arr_4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr_5 = arr_4[1:11]
arr_5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
odd_nums = arr_5[arr_5 % 2 != 0]
odd_nums

array([1, 3, 5, 7, 9])

## Home Work: Install and import python Library for database access

In [10]:
pip install pyodbc

Note: you may need to restart the kernel to use updated packages.


In [12]:
import pyodbc